name: weather_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking
  dio: ^5.4.1
  dio_smart_retry: ^6.0.0
  pretty_dio_logger: ^1.3.1

  # Location
  geolocator: ^11.0.0

  # State Management
  flutter_bloc: ^8.1.4

  # UI
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1

  # Utility
  dartz: ^0.10.1
  equatable: ^2.0.5
  intl: ^0.18.1
  envied: ^0.5.3
  path_provider: ^2.1.2

  # Dependency Injection
  get_it: ^7.6.7

  # JSON Parsing
  json_annotation: ^4.8.1

  # Caching
  hydrated_bloc: ^9.1.4

  # Localization
  easy_localization: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter
  very_good_analysis: ^5.1.0

  # Code Generation
  envied_generator: ^0.5.3
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

  # Testing
  mocktail: ^1.0.3
  bloc_test: ^9.1.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/icons/
    - assets/images/weather/
    - assets/translations/
